"""Lead generation channel definitions."""

CHANNELS = {
    "cold_email": {
        "name": "Cold email",
        "summary": "Fast outbound volume. Works best with targeting, strong copy, and email verification.",
        "base_cost": 90,
        "recommended_budget": 120,
        "time_cost": 7,
        "base_leads": 26,
        "qualified_rate": 0.38,
        "booking_rate": 0.16,
        "lead_value": 0.9,
        "risk": 0.16,
        "skills": {"Copywriting": 0.35, "Targeting": 0.35, "Offer Creation": 0.15, "Analytics": 0.15},
        "learning": ["Copywriting", "Targeting", "Analytics"],
        "unlock": 1,
    },
    "linkedin_outreach": {
        "name": "LinkedIn outreach",
        "summary": "Personal and trust-heavy, but constrained by time and account safety.",
        "base_cost": 40,
        "recommended_budget": 60,
        "time_cost": 8,
        "base_leads": 18,
        "qualified_rate": 0.46,
        "booking_rate": 0.20,
        "lead_value": 1.05,
        "risk": 0.10,
        "skills": {"Targeting": 0.30, "Copywriting": 0.22, "Sales": 0.18, "Offer Creation": 0.18, "Operations": 0.12},
        "learning": ["Targeting", "Sales", "Copywriting"],
        "unlock": 1,
    },
    "linkedin_ads": {
        "name": "LinkedIn ads",
        "summary": "Scalable but unforgiving. Needs budget, analytics, landing pages, and sharp positioning.",
        "base_cost": 160,
        "recommended_budget": 600,
        "time_cost": 5,
        "base_leads": 22,
        "qualified_rate": 0.34,
        "booking_rate": 0.14,
        "lead_value": 1.15,
        "risk": 0.13,
        "skills": {"Targeting": 0.28, "Analytics": 0.26, "Offer Creation": 0.22, "Copywriting": 0.14, "Operations": 0.10},
        "learning": ["Targeting", "Analytics", "Offer Creation"],
        "unlock": 2,
    },
    "apify_workflows": {
        "name": "Apify scraping/workflows",
        "summary": "Improves prospecting scale and niche discovery, but poor workflows create noisy data.",
        "base_cost": 120,
        "recommended_budget": 150,
        "time_cost": 5,
        "base_leads": 32,
        "qualified_rate": 0.33,
        "booking_rate": 0.12,
        "lead_value": 0.95,
        "risk": 0.14,
        "skills": {"Automation": 0.38, "Targeting": 0.30, "Analytics": 0.20, "Operations": 0.12},
        "learning": ["Automation", "Targeting", "Analytics"],
        "unlock": 1,
    },
    "landing_pages": {
        "name": "Landing pages",
        "summary": "Improves conversion from traffic and offers. Slow alone, powerful with ads/content.",
        "base_cost": 110,
        "recommended_budget": 100,
        "time_cost": 7,
        "base_leads": 10,
        "qualified_rate": 0.48,
        "booking_rate": 0.24,
        "lead_value": 1.12,
        "risk": 0.05,
        "skills": {"Offer Creation": 0.30, "Copywriting": 0.28, "Analytics": 0.22, "Operations": 0.20},
        "learning": ["Offer Creation", "Copywriting", "Analytics"],
        "unlock": 1,
    },
    "referrals": {
        "name": "Referrals",
        "summary": "High trust and low cost. Depends on satisfaction, outcomes, and reputation.",
        "base_cost": 20,
        "recommended_budget": 40,
        "time_cost": 3,
        "base_leads": 5,
        "qualified_rate": 0.65,
        "booking_rate": 0.36,
        "lead_value": 1.35,
        "risk": 0.02,
        "skills": {"Client Delivery": 0.34, "Operations": 0.24, "Sales": 0.18, "Offer Creation": 0.14, "Targeting": 0.10},
        "learning": ["Client Delivery", "Operations", "Sales"],
        "unlock": 1,
    },
    "content_marketing": {
        "name": "Content marketing",
        "summary": "Slow at first, but compounds reputation and inbound trust over time.",
        "base_cost": 60,
        "recommended_budget": 80,
        "time_cost": 8,
        "base_leads": 9,
        "qualified_rate": 0.42,
        "booking_rate": 0.18,
        "lead_value": 1.18,
        "risk": 0.04,
        "skills": {"Copywriting": 0.28, "Offer Creation": 0.22, "Targeting": 0.18, "Analytics": 0.18, "Operations": 0.14},
        "learning": ["Copywriting", "Offer Creation", "Analytics"],
        "unlock": 1,
    },
    "sales_calls": {
        "name": "Sales calls",
        "summary": "Turns booked calls into clients. Capacity and skill matter more than raw spend.",
        "base_cost": 0,
        "recommended_budget": 0,
        "time_cost": 5,
        "base_leads": 0,
        "qualified_rate": 0.0,
        "booking_rate": 0.0,
        "lead_value": 1.25,
        "risk": 0.03,
        "skills": {"Sales": 0.45, "Offer Creation": 0.25, "Client Delivery": 0.15, "Operations": 0.15},
        "learning": ["Sales", "Offer Creation"],
        "unlock": 1,
    },
}


def channel_list():
    return [CHANNELS[key] | {"id": key} for key in CHANNELS]

