from __future__ import annotations

import base64
from html import escape
import socket
from pathlib import Path

import pandas as pd
import streamlit as st

from game.achievements import ACHIEVEMENTS
from game.channels import CHANNELS
from game.clients import active_clients, portfolio_workload
from game.data import SKILLS
from game.hiring import ROLE_DATA, SENIORITY, fire_member, hire_member, monthly_payroll, team_effects
from game.persistence import DB_PATH, JSON_FALLBACK_PATH, delete_save, load_game, save_game
from game.simulation import estimate_campaign_cost, simulate_week
from game.state import new_game, normalize_state, refresh_business_metrics
from game.tools import TOOLS, buy_tool, cancel_tool, monthly_tool_cost


APP_DIR = Path(__file__).resolve().parent
ASSET_DIR = APP_DIR / "assets"
COMMAND_CENTER_ASSET = ASSET_DIR / "agency-command-center.png"


NAV_ITEMS = [
    "Dashboard",
    "Run Campaigns",
    "Tools / Subscriptions",
    "Hiring",
    "Clients",
    "Skills / Training",
    "Reports",
    "Achievements",
    "Settings / Save Game",
]

KPI_TOOLTIPS = {
    "Cash": "Cash is your survival buffer. Campaign spend, tool setup fees, payroll, training, and weekly profit/loss all change it.",
    "MRR": "Monthly recurring revenue from active clients. Higher MRR improves stage progression and runway.",
    "Expenses": "Fixed monthly burn from base costs, subscriptions, and payroll. High expenses raise break-even pressure.",
    "Weekly P/L": "Last week's revenue minus campaign spend, training cost, and weekly share of fixed expenses.",
    "Active Clients": "Active clients create MRR but consume delivery capacity. Too many clients without capacity increases churn risk.",
    "Pipeline Leads": "Raw leads generated by campaigns. Leads still need qualification, booked calls, and sales conversion.",
    "Booked Calls": "Sales opportunities waiting to be processed. Low sales capacity or weak follow-up can let calls go stale.",
    "Close Rate": "Lifetime booked-call to client conversion. Sales skill, offer quality, reputation, and sales tools improve it.",
    "Reputation": "Trust in the market. Good targeting and delivery raise it; spammy volume, churn, and mistakes reduce it.",
    "Founder Energy": "Execution quality and available attention. Overloading time or ramping hires can drain it.",
    "Team Size": "People add capacity and leverage but increase payroll, onboarding work, and mistake risk.",
    "Tool Stack": "Tools improve speed, conversion, quality, or capacity. Subscriptions also raise monthly expenses.",
}

CHANNEL_TOOLTIPS = {
    "cold_email": "Fast lead volume. Copywriting, targeting, email verification, and sender reputation strongly influence results.",
    "linkedin_outreach": "Personal outbound. Good targeting and trust help, but intensity can increase restriction risk.",
    "linkedin_ads": "Scalable paid traffic. Budget matters, but targeting, analytics, offer quality, and landing pages decide efficiency.",
    "apify_workflows": "Prospecting automation. Automation and targeting skill improve quality; poor workflows create noisy leads.",
    "landing_pages": "Conversion infrastructure. Helps ads, content, and direct-response traffic turn into qualified calls.",
    "referrals": "Warm demand from satisfied clients. Satisfaction, delivery quality, and reputation drive this channel.",
    "content_marketing": "Slow compounding channel. Copywriting, consistency, and positioning grow inbound demand over time.",
    "sales_calls": "Converts booked calls into clients. Sales skill, offer quality, trust, and call capacity are the key levers.",
}

TRAINING_TOOLTIPS = {
    "Copywriting": "Improves cold email, LinkedIn messages, content, and landing page conversion.",
    "Targeting": "Improves lead quality and reduces wasted outreach or ad spend.",
    "Offer Creation": "Improves booking and close rates by making the promise clearer and more valuable.",
    "Sales": "Improves call capacity, close rate, and ability to turn demand into clients.",
    "Operations": "Improves delivery consistency, reduces churn pressure, and helps teams scale.",
    "Client Delivery": "Improves satisfaction, referrals, retention, and delivery capacity.",
    "Analytics": "Improves optimization, qualification, and paid-channel learning.",
    "Automation": "Improves Apify workflows, prospecting capacity, and operational leverage.",
}

EFFECT_LABELS = {
    "cold_email_leads_multiplier": "more cold email leads",
    "cold_email_time_reduction": "less cold email time",
    "cold_email_quality": "better cold email deliverability/quality",
    "reputation_protection": "lower reputation damage risk",
    "linkedin_outreach_leads_multiplier": "more LinkedIn outreach leads",
    "linkedin_risk": "higher LinkedIn restriction risk",
    "apify_workflows_leads_multiplier": "more Apify workflow leads",
    "targeting_quality": "better targeting quality",
    "booking_rate": "higher booked-call rate",
    "linkedin_ads_quality": "better LinkedIn ads quality",
    "landing_pages_leads_multiplier": "more landing page leads",
    "lost_leads_reduction": "fewer stale/lost leads",
    "operations_quality": "better operations quality",
    "analytics_quality": "better analytics and optimization",
    "qualified_rate": "higher qualification rate",
    "optimization": "better campaign optimization",
    "close_rate": "higher close rate",
    "sales_learning": "faster sales learning",
    "sales_time_reduction": "less sales admin time",
    "copy_quality": "better copy quality",
    "copy_time_reduction": "less copywriting time",
    "generic_copy_risk": "higher generic-copy risk",
    "delivery_capacity": "more delivery capacity",
    "churn_reduction": "lower churn risk",
}


def image_data_uri(path: Path) -> str:
    try:
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        return f"data:image/png;base64,{encoded}"
    except OSError:
        return ""


st.set_page_config(
    page_title="LeadGen Tycoon",
    page_icon="LG",
    layout="wide",
    initial_sidebar_state="expanded",
)


COMMAND_CENTER_URI = image_data_uri(COMMAND_CENTER_ASSET)


CSS = """
<style>
    :root {
        --lg-bg: #eef3f8;
        --lg-surface: #ffffff;
        --lg-ink: #1d2430;
        --lg-muted: #657184;
        --lg-line: #dbe2ea;
        --lg-teal: #0f9f8c;
        --lg-coral: #ff4e4e;
        --lg-gold: #f5b841;
        --lg-navy: #111a27;
        --lg-green: #1f9d55;
        --lg-amber: #b7791f;
        --lg-red: #c53030;
    }
    html,
    body,
    .stApp,
    [data-testid="stAppViewContainer"],
    [data-testid="stMain"],
    section.main {
        background:
            radial-gradient(circle at 16% 0%, rgba(15, 159, 140, 0.12), transparent 28rem),
            radial-gradient(circle at 90% 8%, rgba(245, 184, 65, 0.14), transparent 30rem),
            linear-gradient(180deg, #f4f8fc 0%, #edf3f8 44%, #f7f9fc 100%) !important;
        color: var(--lg-ink) !important;
    }
    [data-testid="stHeader"] {
        background: rgba(244, 248, 252, 0.88) !important;
        border-bottom: 1px solid rgba(219, 226, 234, 0.72);
        backdrop-filter: blur(14px);
    }
    .block-container {
        padding-top: 1.4rem;
        padding-bottom: 2rem;
        max-width: 1220px;
        color: var(--lg-ink);
    }
    .block-container h1,
    .block-container h2,
    .block-container h3,
    .block-container p,
    .block-container label,
    .block-container span,
    .block-container div {
        letter-spacing: 0;
    }
    [data-testid="stSidebar"] {
        background:
            linear-gradient(180deg, rgba(17, 26, 39, 0.95), rgba(24, 35, 50, 0.98)),
            radial-gradient(circle at 50% 0%, rgba(15, 159, 140, 0.22), transparent 18rem);
        border-right: 1px solid rgba(232, 238, 247, 0.12);
    }
    [data-testid="stSidebar"] h1,
    [data-testid="stSidebar"] h2,
    [data-testid="stSidebar"] h3,
    [data-testid="stSidebar"] p,
    [data-testid="stSidebar"] label,
    [data-testid="stSidebar"] span,
    [data-testid="stSidebar"] div {
        color: #e8eef7;
    }
    [data-testid="stSidebar"] [role="radiogroup"] label {
        background: transparent;
        border-radius: 8px;
        padding: 2px 4px;
    }
    [data-testid="stSidebar"] [role="radiogroup"] label:hover {
        background: rgba(255, 255, 255, 0.08);
    }
    .lg-sidebar-kpis {
        display: grid;
        grid-template-columns: 1fr;
        gap: 10px;
        margin: 14px 0 18px;
    }
    .lg-sidebar-kpi {
        background: linear-gradient(180deg, rgba(34, 48, 68, 0.92), rgba(25, 37, 54, 0.96));
        border: 1px solid rgba(232, 238, 247, 0.14);
        border-radius: 8px;
        padding: 12px 14px;
        box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05), 0 10px 22px rgba(0, 0, 0, 0.12);
    }
    .lg-sidebar-kpi span {
        display: block;
        color: #9fb0c5 !important;
        font-size: 0.78rem;
    }
    .lg-sidebar-kpi strong {
        display: block;
        color: #ffffff !important;
        font-size: 1.35rem;
        line-height: 1.2;
        margin-top: 4px;
    }
    [data-testid="stMetric"] {
        background: #ffffff;
        border: 1px solid #dbe2ea;
        border-radius: 8px;
        padding: 14px 16px;
        min-height: 96px;
    }
    .stButton > button {
        border-radius: 8px;
        min-height: 42px;
        font-weight: 700;
        border: 1px solid #0f9f8c !important;
        color: #0f766e !important;
        background: #ffffff !important;
    }
    .stButton > button[kind="primary"],
    .stButton > button[data-testid="baseButton-primary"],
    .stButton > button:hover {
        background: #0f9f8c !important;
        border-color: #0f9f8c !important;
        color: #ffffff !important;
    }
    .stButton > button:focus {
        box-shadow: 0 0 0 3px rgba(15, 159, 140, 0.20) !important;
    }
    .lg-page-title {
        position: relative;
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        gap: 16px;
        min-height: 238px;
        margin-bottom: 18px;
        padding: 26px;
        border-radius: 14px;
        overflow: hidden;
        color: #ffffff;
        background:
            linear-gradient(90deg, rgba(12, 18, 27, 0.95) 0%, rgba(12, 18, 27, 0.82) 38%, rgba(12, 18, 27, 0.28) 100%),
            url("__COMMAND_CENTER_URI__");
        background-size: cover;
        background-position: center;
        border: 1px solid rgba(15, 159, 140, 0.26);
        box-shadow: 0 22px 50px rgba(15, 23, 42, 0.22);
    }
    .lg-page-title::after {
        content: "";
        position: absolute;
        inset: 0;
        background: linear-gradient(180deg, transparent 60%, rgba(5, 10, 18, 0.42) 100%);
        pointer-events: none;
    }
    .lg-page-title > * {
        position: relative;
        z-index: 1;
    }
    .lg-page-title h1 {
        margin: 0;
        max-width: 720px;
        font-size: clamp(2rem, 4vw, 3.8rem);
        line-height: 1.1;
        letter-spacing: 0;
        color: #ffffff;
        text-shadow: 0 8px 26px rgba(0, 0, 0, 0.28);
    }
    .lg-page-title .lg-subtle,
    .lg-page-title p {
        max-width: 620px;
        color: #d8e4f4 !important;
    }
    .lg-hero-eyebrow {
        display: inline-flex;
        align-items: center;
        gap: 8px;
        margin-bottom: 12px;
        padding: 6px 10px;
        border-radius: 999px;
        background: rgba(15, 159, 140, 0.18);
        border: 1px solid rgba(95, 230, 207, 0.36);
        color: #dffdf6;
        font-size: 0.76rem;
        font-weight: 800;
        text-transform: uppercase;
    }
    .lg-week-card {
        min-width: 178px;
        padding: 14px 15px;
        border-radius: 10px;
        background: rgba(255, 255, 255, 0.92);
        color: #1d2430;
        border: 1px solid rgba(255, 255, 255, 0.62);
        box-shadow: 0 16px 34px rgba(0, 0, 0, 0.24);
    }
    .lg-week-card .lg-small-label {
        color: #617089;
    }
    .lg-week-card strong {
        display: block;
        margin: 5px 0 3px;
        font-size: 1.75rem;
        line-height: 1;
    }
    .lg-xp-track {
        height: 8px;
        margin-top: 10px;
        border-radius: 999px;
        background: #dce6f0;
        overflow: hidden;
    }
    .lg-xp-track span {
        display: block;
        height: 100%;
        border-radius: inherit;
        background: linear-gradient(90deg, #0f9f8c, #f5b841);
    }
    .lg-subtle {
        color: var(--lg-muted);
        font-size: 0.94rem;
        line-height: 1.45;
    }
    .lg-panel {
        background: rgba(255, 255, 255, 0.94);
        border: 1px solid rgba(201, 212, 226, 0.9);
        border-radius: 10px;
        padding: 16px;
        margin-bottom: 12px;
        box-shadow: 0 12px 28px rgba(15, 23, 42, 0.06);
    }
    .lg-callout {
        background: #edfdf8;
        border: 1px solid #b7eee0;
        border-radius: 8px;
        padding: 12px 14px;
        color: #164c43;
        margin: 8px 0 14px 0;
    }
    .lg-warning {
        background: #fff8e6;
        border: 1px solid #f2d28b;
        color: #684b11;
    }
    .lg-danger {
        background: #fff1f1;
        border: 1px solid #f3b7b7;
        color: #7c1d1d;
    }
    .lg-small-label {
        color: #657184;
        font-size: 0.78rem;
        text-transform: uppercase;
        letter-spacing: 0;
        font-weight: 700;
    }
    .lg-kpi-grid {
        display: grid;
        grid-template-columns: repeat(4, minmax(0, 1fr));
        gap: 12px;
        margin: 10px 0 20px;
    }
    .lg-kpi {
        position: relative;
        overflow: hidden;
        background: linear-gradient(180deg, rgba(255, 255, 255, 0.96), rgba(249, 252, 255, 0.96));
        border: 1px solid rgba(201, 212, 226, 0.95);
        border-radius: 12px;
        padding: 14px 15px;
        min-height: 104px;
        box-shadow: 0 12px 24px rgba(15, 23, 42, 0.06);
    }
    .lg-kpi::before {
        content: "";
        position: absolute;
        left: 0;
        top: 0;
        bottom: 0;
        width: 5px;
        background: linear-gradient(180deg, #0f9f8c, #f5b841);
    }
    .lg-kpi-top {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 8px;
        margin-bottom: 6px;
    }
    .lg-kpi-code {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 34px;
        height: 34px;
        border-radius: 9px;
        background: #111a27;
        color: #ffffff !important;
        font-size: 0.72rem;
        font-weight: 900;
        box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.12);
    }
    .lg-kpi strong {
        display: block;
        margin-top: 6px;
        font-size: 1.55rem;
        color: #1d2430;
        line-height: 1.1;
    }
    .lg-kpi span {
        color: #657184;
        font-size: 0.82rem;
    }
    .lg-help {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        position: relative;
        width: 17px;
        height: 17px;
        margin-left: 6px;
        border-radius: 999px;
        border: 1px solid #b8c5d4;
        color: #526173;
        background: #f8fafc;
        font-size: 11px;
        font-weight: 800;
        cursor: help;
        vertical-align: middle;
        overflow: visible;
    }
    .lg-help:hover {
        border-color: #0f9f8c;
        color: #0f766e;
        background: #e8fbf7;
    }
    .lg-help .lg-tooltip-text {
        position: absolute;
        left: 50%;
        bottom: calc(100% + 8px);
        transform: translateX(-50%);
        width: max-content;
        max-width: min(280px, 78vw);
        padding: 9px 11px;
        border-radius: 7px;
        background: #ffffff;
        color: #1d2430;
        border: 1px solid #dbe2ea;
        box-shadow: 0 10px 30px rgba(15, 23, 42, 0.16);
        font-size: 0.78rem;
        font-weight: 600;
        line-height: 1.35;
        text-align: left;
        white-space: normal;
        z-index: 9999;
        pointer-events: none;
        visibility: hidden;
        opacity: 0;
        transition: opacity 120ms ease;
    }
    .lg-help .lg-tooltip-text::after {
        content: "";
        position: absolute;
        left: 50%;
        top: 100%;
        transform: translateX(-50%);
        border: 5px solid transparent;
        border-top-color: #ffffff;
        pointer-events: none;
    }
    .lg-help:hover .lg-tooltip-text,
    .lg-help:focus .lg-tooltip-text,
    .lg-help:focus-within .lg-tooltip-text {
        visibility: visible;
        opacity: 1;
    }
    .lg-list-item {
        border-bottom: 1px solid #e7ecf2;
        padding: 8px 0;
    }
    .lg-list-item:last-child {
        border-bottom: 0;
    }
    .lg-chart-card {
        background: rgba(255, 255, 255, 0.95);
        border: 1px solid rgba(201, 212, 226, 0.95);
        border-radius: 12px;
        padding: 16px 16px 10px;
        margin-bottom: 14px;
        box-shadow: 0 12px 26px rgba(15, 23, 42, 0.06);
    }
    .lg-chart-card h3 {
        color: #1d2430;
        font-size: 1rem;
        line-height: 1.2;
        margin: 0 0 12px;
    }
    .lg-chart-card svg {
        display: block;
        width: 100%;
        height: auto;
    }
    .lg-chart-axis {
        color: #657184;
        font-size: 11px;
    }
    [data-testid="stDataFrame"],
    [data-testid="stTable"] {
        background: #ffffff;
        border-radius: 8px;
    }
    @media (max-width: 800px) {
        .block-container {
            padding-left: 0.8rem;
            padding-right: 0.8rem;
        }
        .lg-kpi-grid {
            grid-template-columns: repeat(2, minmax(0, 1fr));
        }
        .lg-page-title {
            display: block;
            min-height: 280px;
            padding: 20px;
            background-position: 58% center;
        }
        .lg-week-card {
            margin-top: 18px;
            min-width: 0;
        }
    }
    @media (max-width: 560px) {
        .lg-kpi-grid {
            grid-template-columns: 1fr;
        }
    }
</style>
"""

CSS = CSS.replace("__COMMAND_CENTER_URI__", COMMAND_CENTER_URI)

st.markdown(CSS, unsafe_allow_html=True)


def money(value: float) -> str:
    sign = "-" if value < 0 else ""
    return f"{sign}${abs(value):,.0f}"


def percent(value: float) -> str:
    return f"{value:.1%}"


def tooltip_badge(text: str) -> str:
    tip = escape(str(text), quote=True)
    return (
        f'<span class="lg-help" title="{tip}" data-tooltip="{tip}" aria-label="{tip}" tabindex="0">'
        f'?<span class="lg-tooltip-text" aria-hidden="true">{tip}</span></span>'
    )


def tooltip_line(label: str, text: str) -> str:
    return f'<span class="lg-subtle">{escape(label)} {tooltip_badge(text)}</span>'


def effect_summary(effects: dict) -> str:
    readable = []
    for key, value in effects.items():
        label = EFFECT_LABELS.get(key, key.replace("_", " "))
        if isinstance(value, (int, float)):
            if abs(value) < 1:
                readable.append(f"{label}: {value:+.0%}")
            else:
                readable.append(f"{label}: {value:+g}")
        else:
            readable.append(label)
    return "; ".join(readable) if readable else "This affects gameplay through its listed benefits and tradeoffs."


def queue_notification(message: str):
    st.session_state.setdefault("pending_notifications", []).append(message)


def flush_notifications():
    pending = st.session_state.get("pending_notifications", [])
    if not pending:
        return
    st.session_state.pending_notifications = []
    for message in pending:
        st.toast(message)


def get_lan_hint() -> str:
    try:
        host = socket.gethostbyname(socket.gethostname())
        if host and not host.startswith("127."):
            return f"http://{host}:8501"
    except OSError:
        pass
    return "http://YOUR-COMPUTER-IP:8501"


def default_actions():
    return {
        "campaigns": {
            "cold_email": {"enabled": True, "intensity": 1, "budget": 80},
            "linkedin_outreach": {"enabled": True, "intensity": 1, "budget": 40},
            "sales_calls": {"enabled": True, "intensity": 1, "budget": 0},
        },
        "training": {skill: 0 for skill in SKILLS},
    }


def init_session():
    if "game" not in st.session_state:
        saved = load_game()
        st.session_state.game = saved if saved else new_game()
    st.session_state.game = normalize_state(st.session_state.game)
    if "weekly_actions" not in st.session_state:
        st.session_state.weekly_actions = default_actions()
    if st.session_state.get("nav") not in NAV_ITEMS:
        st.session_state.nav = "Dashboard"
    if st.session_state.get("nav_radio") not in NAV_ITEMS:
        st.session_state.nav_radio = st.session_state.nav
    if "pending_notifications" not in st.session_state:
        st.session_state.pending_notifications = []


def persist():
    refresh_business_metrics(st.session_state.game)
    try:
        save_game(st.session_state.game)
        st.session_state.save_error = ""
    except OSError as exc:
        st.session_state.save_error = f"Save failed: {exc}"


def run_week():
    completed_week = st.session_state.game.get("week", 1)
    st.session_state.game = simulate_week(st.session_state.game, st.session_state.weekly_actions)
    unlocked = st.session_state.game.get("last_achievements", [])
    persist()
    queue_notification(f"Week {completed_week} simulated and saved.")
    for achievement in unlocked:
        queue_notification(
            f"Achievement unlocked: {achievement['name']} - {achievement['description']} (+{achievement.get('xp', 0)} XP)"
        )


def stage_index(stage_name: str) -> int:
    names = ["Solo freelancer", "Specialist", "Small agency", "Growing agency", "Established business", "Market leader"]
    return names.index(stage_name) + 1 if stage_name in names else 1


def page_header(title: str, subtitle: str = ""):
    state = st.session_state.game
    week_tip = (
        "Current simulation week, level, and business stage. Stages are based on MRR, active clients, and reputation."
    )
    xp_progress = min(100, int((state.get("xp", 0) % 250) / 250 * 100))
    st.markdown(
        f"""
        <div class="lg-page-title">
          <div>
            <div class="lg-hero-eyebrow">Agency command center</div>
            <h1>{escape(title)}</h1>
            <p>{escape(subtitle) if subtitle else "Plan campaigns, manage capacity, and grow the agency one week at a time."}</p>
          </div>
          <div class="lg-week-card" title="{escape(week_tip, quote=True)}">
            <div class="lg-small-label">Current week {tooltip_badge(week_tip)}</div>
            <strong>Week {state['week']}</strong>
            <div class="lg-subtle">Level {state['level']} - {escape(state['stage'])}</div>
            <div class="lg-xp-track" aria-label="XP progress"><span style="width:{xp_progress}%"></span></div>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def kpi_grid(state):
    clients = active_clients(state)
    lifetime_booked = state["metrics"].get("lifetime_booked_calls", 0)
    lifetime_closed = state["metrics"].get("lifetime_clients_closed", 0)
    close_rate = lifetime_closed / lifetime_booked if lifetime_booked else 0
    items = [
        ("Cash", "CASH", money(state["cash"]), "Runway and survival"),
        ("MRR", "MRR", money(state["mrr"]), "Active recurring revenue"),
        ("Expenses", "BURN", money(state["monthly_expenses"]), "Monthly fixed burn"),
        ("Weekly P/L", "P/L", money(state.get("weekly_profit", 0)), "Last simulated week"),
        ("Active Clients", "CLNT", f"{len(clients)}", "Delivery workload"),
        ("Pipeline Leads", "LEAD", f"{state['pipeline'].get('leads', 0):,.0f}", "Raw generated demand"),
        ("Booked Calls", "CALL", f"{state['pipeline'].get('booked_calls', 0):,.0f}", "Sales opportunities"),
        ("Close Rate", "WIN", percent(close_rate), "Lifetime booked-to-client"),
        ("Reputation", "REP", f"{state['reputation']:.0f}/100", "Trust and market signal"),
        ("Founder Energy", "NRG", f"{state['founder_energy']:.0f}/100", "Execution quality"),
        ("Team Size", "TEAM", f"{len(state.get('team', []))}", "Capacity and payroll"),
        ("Tool Stack", "TOOL", f"{len(state.get('tools', []))}", "Systems and subscriptions"),
    ]
    cards = []
    for label, code, value, hint in items:
        tooltip = KPI_TOOLTIPS.get(label, hint)
        cards.append(
            f'<div class="lg-kpi" title="{escape(tooltip, quote=True)}">'
            f'<div class="lg-kpi-top">'
            f'<span>{escape(label)} {tooltip_badge(tooltip)}</span>'
            f'<span class="lg-kpi-code">{escape(code)}</span>'
            f'</div>'
            f'<strong>{escape(value)}</strong>'
            f'<span>{escape(hint)}</span>'
            f'</div>'
        )
    st.markdown(f'<div class="lg-kpi-grid">{"".join(cards)}</div>', unsafe_allow_html=True)


def history_df():
    history = st.session_state.game.get("history", [])
    if not history:
        history = [
            {
                "week": 0,
                "cash": st.session_state.game["cash"],
                "mrr": st.session_state.game.get("mrr", 0),
                "revenue": 0,
                "expenses": 0,
                "profit": 0,
                "leads": 0,
                "qualified_leads": 0,
                "booked_calls": 0,
                "clients_closed": 0,
                "active_clients": len(active_clients(st.session_state.game)),
            }
        ]
    df = pd.DataFrame(history)
    required_columns = {
        "week": 0,
        "cash": st.session_state.game.get("cash", 0),
        "mrr": st.session_state.game.get("mrr", 0),
        "revenue": 0,
        "expenses": 0,
        "profit": 0,
        "leads": 0,
        "qualified_leads": 0,
        "booked_calls": 0,
        "clients_closed": 0,
        "active_clients": len(active_clients(st.session_state.game)),
        "reputation": st.session_state.game.get("reputation", 0),
        "founder_energy": st.session_state.game.get("founder_energy", 0),
    }
    for column, default in required_columns.items():
        if column not in df:
            df[column] = default
    return df


def channel_df():
    rows = []
    for channel_id, perf in st.session_state.game.get("channel_performance", {}).items():
        channel = CHANNELS[channel_id]
        leads = perf.get("leads", 0)
        qualified = perf.get("qualified", 0)
        booked = perf.get("booked", 0)
        clients = perf.get("clients", 0)
        spend = perf.get("spend", 0)
        rows.append(
            {
                "Channel": channel["name"],
                "Leads": leads,
                "Qualified": qualified,
                "Booked": booked,
                "Clients": clients,
                "Spend": spend,
                "Booking Rate": booked / qualified if qualified else 0,
                "Close Rate": clients / booked if booked else 0,
                "Cost / Lead": spend / leads if leads else 0,
                "Cost / Client": spend / clients if clients else 0,
            }
        )
    return pd.DataFrame(rows)


def formatted_channel_df():
    df = channel_df()
    if df.empty:
        return df
    formatted = df.copy()
    for column in ["Spend", "Cost / Lead", "Cost / Client"]:
        formatted[column] = formatted[column].map(money)
    for column in ["Booking Rate", "Close Rate"]:
        formatted[column] = formatted[column].map(percent)
    return formatted


def channel_column_config():
    return {
        "Channel": st.column_config.TextColumn("Channel", help="The acquisition source that produced these results."),
        "Leads": st.column_config.NumberColumn("Leads", help="Raw contacts or inbound prospects generated by the channel."),
        "Qualified": st.column_config.NumberColumn("Qualified", help="Leads that fit the offer and are worth follow-up."),
        "Booked": st.column_config.NumberColumn("Booked", help="Qualified leads that turned into sales calls."),
        "Clients": st.column_config.NumberColumn("Clients", help="Closed clients attributed to this channel."),
        "Spend": st.column_config.TextColumn("Spend", help="Campaign spend attributed to this channel."),
        "Booking Rate": st.column_config.TextColumn("Booking Rate", help="Booked calls divided by qualified leads."),
        "Close Rate": st.column_config.TextColumn("Close Rate", help="Clients closed divided by booked calls."),
        "Cost / Lead": st.column_config.TextColumn("Cost / Lead", help="Spend divided by raw leads generated."),
        "Cost / Client": st.column_config.TextColumn("Cost / Client", help="Spend divided by clients closed."),
    }


def client_column_config():
    return {
        "name": st.column_config.TextColumn("Client", help="Client account name."),
        "niche": st.column_config.TextColumn("Niche", help="The market segment this client represents."),
        "source": st.column_config.TextColumn("Source", help="The channel or event that created the client."),
        "monthly_value": st.column_config.NumberColumn("Monthly Value", format="$%d", help="Recurring monthly revenue from this client."),
        "satisfaction": st.column_config.ProgressColumn(
            "Satisfaction",
            min_value=0,
            max_value=100,
            format="%.0f",
            help="Higher satisfaction lowers churn risk and improves referral chance.",
        ),
        "delivery_workload": st.column_config.NumberColumn("Workload", format="%.1f", help="Delivery capacity consumed by this client."),
        "churn_risk": st.column_config.ProgressColumn(
            "Churn Risk",
            min_value=0,
            max_value=100,
            format="%.0f",
            help="Estimated monthly risk based on satisfaction, delivery pressure, and operations quality.",
        ),
        "referral_potential": st.column_config.ProgressColumn(
            "Referral Potential",
            min_value=0,
            max_value=100,
            format="%.0f",
            help="Chance this client can create referral opportunities when satisfaction is high.",
        ),
        "age_weeks": st.column_config.NumberColumn("Age", format="%d weeks", help="How long this client has been active."),
    }


def svg_chart_panel(title, series):
    width = 720
    height = 260
    left = 58
    right = 18
    top = 18
    bottom = 38
    values = [float(value) for item in series for value in item["values"]]
    if not values:
        values = [0]
    minimum = min(0, min(values))
    maximum = max(values)
    if maximum == minimum:
        maximum += 1
    x_values = []
    max_points = max((len(item["values"]) for item in series), default=1)
    for index in range(max_points):
        x = left + (width - left - right) * (index / max(1, max_points - 1))
        x_values.append(x)

    grid_lines = []
    for index in range(5):
        ratio = index / 4
        y = top + (height - top - bottom) * ratio
        label_value = maximum - (maximum - minimum) * ratio
        label = money(label_value) if maximum >= 1000 else f"{label_value:,.0f}"
        grid_lines.append(
            f'<line x1="{left}" y1="{y:.1f}" x2="{width - right}" y2="{y:.1f}" stroke="#e8edf3" stroke-width="1" />'
            f'<text x="10" y="{y + 4:.1f}" fill="#657184" font-size="11">{escape(label)}</text>'
        )

    lines = []
    for item in series:
        points = []
        for index, value in enumerate(item["values"]):
            x = x_values[index]
            y = top + (height - top - bottom) * ((maximum - float(value)) / (maximum - minimum))
            points.append(f"{x:.1f},{y:.1f}")
        if len(points) == 1:
            points.append(f"{width - right:.1f},{points[0].split(',')[1]}")
        lines.append(
            f'<polyline points="{" ".join(points)}" fill="none" stroke="{item["color"]}" stroke-width="3" '
            f'stroke-linecap="round" stroke-linejoin="round" />'
        )

    legend = ""
    for index, item in enumerate(series):
        x = left + index * 150
        y = height - 12
        legend += (
            f'<circle cx="{x}" cy="{y - 4}" r="4" fill="{item["color"]}" />'
            f'<text x="{x + 10}" y="{y}" fill="#657184" font-size="12">{escape(item["label"])}</text>'
        )

    html = f"""
    <div class="lg-chart-card">
      <h3>{escape(title)}</h3>
      <svg viewBox="0 0 {width} {height}" role="img" aria-label="{escape(title)} chart">
        <rect x="0" y="0" width="{width}" height="{height}" fill="#ffffff" />
        {"".join(grid_lines)}
        {"".join(lines)}
        {legend}
      </svg>
    </div>
    """
    st.markdown(html, unsafe_allow_html=True)


def render_feedback(state):
    tip = "This explains why the last week performed the way it did, including channel quality, cash flow, delivery pressure, and event impacts."
    items = "".join(
        f'<div class="lg-list-item">{escape(str(item))}</div>' for item in state.get("last_feedback", [])[:8]
    )
    st.markdown("### Educational Feedback", help=tip)
    st.markdown(
        f"""
        <div class="lg-panel">
          {items}
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_run_week_button(label="Run Week", key="run_week"):
    if st.button(
        label,
        key=key,
        type="primary",
        use_container_width=True,
        help="Advance the simulator by one week using the saved campaign and training plan. This updates cash, pipeline, clients, events, churn risk, skills, and achievements.",
    ):
        run_week()
        st.rerun()


def dashboard_page():
    state = st.session_state.game
    page_header("LeadGen Tycoon", "Run a local-first B2B lead generation business simulator, one week at a time.")
    kpi_grid(state)

    left, right = st.columns([1.6, 1], gap="large")
    df = history_df()
    with left:
        svg_chart_panel(
            "Business Trend",
            [
                {"label": "Cash", "color": "#0f9f8c", "values": df["cash"].tolist()},
                {"label": "MRR", "color": "#1f9d55", "values": df["mrr"].tolist()},
                {"label": "Profit", "color": "#b7791f", "values": df["profit"].tolist()},
            ],
        )

        pipeline_series = [
            {"label": "Leads", "color": "#2563eb", "values": df["leads"].tolist()},
            {"label": "Active clients", "color": "#7c3aed", "values": df["active_clients"].tolist()},
        ]
        if "booked_calls" in df:
            pipeline_series.insert(1, {"label": "Booked calls", "color": "#0f9f8c", "values": df["booked_calls"].tolist()})
        svg_chart_panel("Pipeline Trend", pipeline_series)

    with right:
        render_run_week_button("Run Planned Week", key="dashboard_run_planned_week")
        plan = st.session_state.weekly_actions
        planned = [CHANNELS[cid]["name"] for cid, cfg in plan.get("campaigns", {}).items() if cfg.get("enabled")]
        weekly_plan_tip = "These are the campaign choices saved for the next weekly simulation. Editing them does not spend money until you run the week."
        st.markdown("**Weekly Plan**", help=weekly_plan_tip)
        st.markdown(
            f"""
            <div class="lg-panel">
              <div style="font-weight:700;color:#1d2430;margin:6px 0;">{", ".join(planned) if planned else "No campaigns selected"}</div>
              <div class="lg-subtle">Edit the plan in Run Campaigns and Skills / Training before simulating the next week.</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        render_feedback(state)

    st.subheader("Channel Performance")
    st.caption(
        "How to read this table",
        help="Compare channels by qualified leads, booked calls, clients, spend, and cost per result. More raw leads is not always better.",
    )
    st.dataframe(
        formatted_channel_df(),
        use_container_width=True,
        hide_index=True,
        column_config=channel_column_config(),
    )


def run_campaigns_page():
    page_header("Run Campaigns", "Choose weekly acquisition actions. Higher intensity increases volume, cost, workload, and risk.")
    actions = st.session_state.weekly_actions
    with st.form("campaign_plan"):
        new_campaigns = {}
        total_cost = 0
        total_time = 0
        for channel_id, channel in CHANNELS.items():
            current = actions.get("campaigns", {}).get(channel_id, {"enabled": False, "intensity": 1, "budget": 0})
            with st.expander(channel["name"], expanded=channel_id in ("cold_email", "linkedin_outreach", "sales_calls")):
                st.write(channel["summary"])
                st.markdown(
                    f'<span class="lg-subtle">Gameplay influence {tooltip_badge(CHANNEL_TOOLTIPS.get(channel_id, channel["summary"]))}</span>',
                    unsafe_allow_html=True,
                )
                enabled = st.checkbox(
                    "Run this channel next week",
                    value=current.get("enabled", False),
                    key=f"{channel_id}_enabled",
                    help="If enabled, this channel consumes time and/or spend next week and can generate leads, qualified leads, booked calls, risk, and skill XP.",
                )
                intensity = st.slider(
                    "Intensity",
                    1,
                    3,
                    int(current.get("intensity", 1)),
                    key=f"{channel_id}_intensity",
                    help="Higher intensity increases volume and learning, but also increases founder time, spend, and channel-specific risk. Intensity 3 is aggressive.",
                )
                budget = 0
                if channel_id != "sales_calls":
                    budget = st.number_input(
                        "Extra budget",
                        min_value=0,
                        max_value=10000,
                        value=int(current.get("budget", channel["recommended_budget"])),
                        step=25,
                        key=f"{channel_id}_budget",
                        help="Extra spend can increase lead volume, especially for paid/scaled channels. It still needs skill, targeting, and offer quality to convert efficiently.",
                    )
                estimated_cost = estimate_campaign_cost(channel_id, intensity, budget) if enabled else 0
                estimated_time = channel["time_cost"] * intensity if enabled else 0
                st.caption(f"Estimated weekly cost: {money(estimated_cost)} | Founder time: {estimated_time:.0f}h")
                new_campaigns[channel_id] = {"enabled": enabled, "intensity": intensity, "budget": budget}
                total_cost += estimated_cost
                total_time += estimated_time

        submitted = st.form_submit_button(
            "Save Campaign Plan",
            type="primary",
            use_container_width=True,
            help="Saves these campaign choices for the next weekly simulation. It does not spend money until you run the week.",
        )
        if submitted:
            actions["campaigns"] = new_campaigns
            st.session_state.weekly_actions = actions
            st.success("Campaign plan saved.")

    st.markdown(
        f"""
        <div class="lg-callout">
          Planned campaign spend is about <strong>{money(total_cost)}</strong> and direct founder time is about <strong>{total_time:.0f} hours</strong>.
          The simulator will also account for training, team onboarding, client delivery, payroll, and subscriptions.
        </div>
        """,
        unsafe_allow_html=True,
    )
    render_run_week_button("Run Week With This Plan", key="campaigns_run_week")


def tools_page():
    state = st.session_state.game
    page_header("Tools / Subscriptions", "Buy systems that improve capacity, quality, conversion, and follow-up. Every subscription raises break-even revenue.")
    st.metric(
        "Current monthly tool cost",
        money(monthly_tool_cost(state)),
        help="Total recurring subscription cost. This is added to monthly expenses and raises the revenue needed to stay profitable.",
    )

    owned_ids = {tool["id"] for tool in state.get("tools", [])}
    if state.get("tools"):
        st.subheader("Active Subscriptions")
        for tool in state["tools"]:
            active_tip = f"Active effect: {effect_summary(tool.get('effects', {}))}. This tool is also adding {money(tool['monthly_cost'])}/month to expenses."
            cols = st.columns([3, 1, 1])
            cols[0].markdown(f"**{tool['name']}** {tooltip_badge(active_tip)} - {tool['benefits']}", unsafe_allow_html=True)
            cols[1].write(money(tool["monthly_cost"]) + "/mo")
            if cols[2].button(
                "Cancel",
                key=f"cancel_{tool['id']}",
                help="Removes this monthly cost and its gameplay benefits starting now.",
            ):
                ok, msg = cancel_tool(state, tool["id"])
                persist()
                queue_notification(msg)
                st.rerun()

    st.subheader("Marketplace")
    for tool in TOOLS:
        locked = stage_index(state["stage"]) < tool.get("unlock_stage", 1)
        owned = tool["id"] in owned_ids
        tool_tip = (
            f"Setup cost: {money(tool['setup_cost'])}. Monthly cost: {money(tool['monthly_cost'])}. "
            f"Gameplay effects: {effect_summary(tool.get('effects', {}))}."
        )
        st.markdown(
            f"""
            <div class="lg-panel">
              <div style="display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap;">
                <div style="min-width:260px;flex:1;">
                  <div style="font-weight:800;color:#1d2430;margin-bottom:4px;">{escape(tool['name'])}{tooltip_badge(tool_tip)}</div>
                  <div class="lg-subtle">{escape(tool['benefits'])}</div>
                  <div class="lg-subtle" style="margin-top:6px;">Tradeoff: {escape(tool['downside'])}</div>
                </div>
                <div style="min-width:130px;">
                  <div class="lg-small-label">Monthly</div>
                  <div style="font-size:1.5rem;font-weight:800;color:#1d2430;">{money(tool['monthly_cost'])}</div>
                  <div class="lg-subtle">Setup {money(tool['setup_cost'])}</div>
                </div>
              </div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        action_cols = st.columns([4, 1.2])
        with action_cols[1]:
            if owned:
                st.success("Owned")
                st.markdown(tooltip_line("Status", "You already own this subscription, so its benefits and monthly cost are active."), unsafe_allow_html=True)
            elif locked:
                st.info("Unlock later")
                st.markdown(tooltip_line("Status", "This tool is locked until your business reaches the required stage."), unsafe_allow_html=True)
            else:
                disabled = state["cash"] < tool["setup_cost"]
                if st.button(
                    "Buy",
                    key=f"buy_{tool['id']}",
                    disabled=disabled,
                    use_container_width=True,
                    help=tool_tip if not disabled else f"You need {money(tool['setup_cost'])} cash for setup before buying this tool.",
                ):
                    ok, msg = buy_tool(state, tool["id"])
                    persist()
                    queue_notification(msg)
                    st.rerun()


def hiring_page():
    state = st.session_state.game
    page_header("Hiring", "Add capacity carefully. Payroll makes growth easier and bankruptcy faster.")
    st.metric(
        "Monthly payroll",
        money(monthly_payroll(state)),
        help="Total team salary added to monthly expenses. Payroll creates capacity but can bankrupt the business if MRR does not cover it.",
    )

    role_id = st.selectbox(
        "Role",
        list(ROLE_DATA.keys()),
        format_func=lambda key: ROLE_DATA[key]["role"],
        key="hire_role_id",
        help="Each role changes different parts of the business: acquisition capacity, quality, sales capacity, delivery capacity, operations, churn, or founder time.",
    )
    seniority = st.radio(
        "Seniority",
        list(SENIORITY.keys()),
        horizontal=True,
        key="hire_seniority",
        help="Junior hires are cheaper but weaker and riskier. Senior hires cost more but ramp faster, make fewer mistakes, and produce stronger results.",
    )
    role = ROLE_DATA[role_id]
    salary = round(role["base_salary"] * SENIORITY[seniority]["salary"])
    onboarding = round(salary * 0.25)
    training_weeks = max(0, role["training_requirement"] + SENIORITY[seniority]["training"])
    role_tip = (
        f"Time relief: {role['time_relief']}h/month-equivalent in the weekly model. "
        f"Delivery capacity: +{role['delivery_capacity']}. "
        f"Productivity: {effect_summary(role.get('productivity_effect', {}))}. "
        f"Quality: {effect_summary(role.get('quality_effect', {}))}. "
        f"Training ramp: {training_weeks} week(s)."
    )
    st.markdown(
        f"""
        <div class="lg-panel">
          <strong>{seniority} {role['role']}{tooltip_badge(role_tip)}</strong><br>
          Monthly salary: <strong>{money(salary)}</strong> | Onboarding cost now: <strong>{money(onboarding)}</strong><br>
          Training ramp: <strong>{training_weeks} week(s)</strong><br>
          <span class="lg-subtle">Productivity: {escape(effect_summary(role.get('productivity_effect', {})))}</span><br>
          <span class="lg-subtle">Quality: {escape(effect_summary(role.get('quality_effect', {})))}</span><br>
          <span class="lg-subtle">Risk: {escape(role['mistakes'])}</span>
        </div>
        """,
        unsafe_allow_html=True,
    )
    if st.button(
        "Hire Candidate",
        key="hire_candidate",
        type="primary",
        use_container_width=True,
        help="Pays onboarding cost now, adds salary to monthly expenses, and starts the hire's training ramp.",
    ):
        ok, msg = hire_member(state, role_id, seniority)
        if ok:
            persist()
            queue_notification(msg)
            st.rerun()
        else:
            st.error(msg)

    if state.get("team"):
        st.subheader("Team")
        for member in state["team"]:
            cols = st.columns([2, 1, 1, 1])
            cols[0].write(f"**{member['seniority']} {member['role']}**")
            cols[1].write(money(member["salary"]) + "/mo")
            cols[2].write(f"Training: {member.get('training_weeks_remaining', 0)}w")
            if cols[3].button(
                "Remove",
                key=f"fire_{member['id']}",
                help="Removes salary and role benefits. Costs severance and slightly hurts reputation.",
            ):
                ok, msg = fire_member(state, member["id"])
                persist()
                queue_notification(msg)
                st.rerun()
    else:
        st.info("No hires yet. Early on, hiring is most useful when a channel is working but time or delivery capacity is the bottleneck.")
        st.markdown(
            tooltip_line(
                "Hiring signal",
                "Good first hires usually solve a clear bottleneck: sales calls piling up, delivery over capacity, or a channel that works but needs more execution.",
            ),
            unsafe_allow_html=True,
        )

    effects = team_effects(state)
    st.subheader("Team Effects")
    st.markdown(
        tooltip_line(
            "What these values mean",
            "These are the current aggregated team modifiers. They feed into channel volume, quality, call capacity, delivery capacity, churn reduction, mistake risk, and founder time relief.",
        ),
        unsafe_allow_html=True,
    )
    st.json({key: round(value, 3) for key, value in effects.items() if value})


def clients_page():
    state = st.session_state.game
    page_header("Clients", "Client economics determine whether lead generation becomes a real business.")
    clients = active_clients(state)
    delivery_capacity = 8 + state["skills"].get("Client Delivery", 1) * 2.4 + state["skills"].get("Operations", 1) * 1.4 + team_effects(state).get("delivery_capacity", 0)
    workload = portfolio_workload(state)
    cols = st.columns(4)
    cols[0].metric("Active clients", len(clients), help="Clients currently paying MRR and consuming delivery capacity.")
    cols[1].metric("Portfolio MRR", money(state["mrr"]), help="Recurring revenue from active clients.")
    cols[2].metric("Workload", f"{workload:.1f}", help="Total delivery workload required by active clients.")
    cols[3].metric("Capacity", f"{delivery_capacity:.1f}", help="Available delivery capacity from founder skills, team, and tools.")
    if workload > delivery_capacity:
        st.markdown('<div class="lg-callout lg-warning">Delivery is over capacity. Expect satisfaction decay, churn risk, and weaker referrals.</div>', unsafe_allow_html=True)

    if clients:
        df = pd.DataFrame(clients)
        st.markdown(
            tooltip_line(
                "Client health",
                "Satisfaction and churn risk are affected by delivery capacity, operations, client workload, founder energy, and team quality.",
            ),
            unsafe_allow_html=True,
        )
        st.dataframe(
            df[["name", "niche", "source", "monthly_value", "satisfaction", "delivery_workload", "churn_risk", "referral_potential", "age_weeks"]],
            use_container_width=True,
            hide_index=True,
            column_config=client_column_config(),
        )
    else:
        st.info("No active clients yet. Generate booked calls and run sales calls to close your first account.")
        st.markdown(
            tooltip_line(
                "Client acquisition",
                "Clients come from booked calls processed through sales. Better lead quality, offer clarity, reputation, and sales skill improve close rates.",
            ),
            unsafe_allow_html=True,
        )

    churned = [client for client in state.get("clients", []) if client.get("status") == "churned"]
    if churned:
        st.subheader("Churned Clients")
        st.markdown(
            tooltip_line(
                "Why clients churned",
                "Churn usually comes from low satisfaction, delivery overload, weak operations, or random client-side events.",
            ),
            unsafe_allow_html=True,
        )
        st.dataframe(
            pd.DataFrame(churned)[["name", "source", "monthly_value", "satisfaction", "churn_risk"]],
            use_container_width=True,
            hide_index=True,
            column_config=client_column_config(),
        )


def skills_page():
    state = st.session_state.game
    page_header("Skills / Training", "Skills improve through training and repeated use. Higher skills raise quality and reduce costly mistakes.")
    cols = st.columns(4)
    for index, skill in enumerate(SKILLS):
        with cols[index % 4]:
            level = state["skills"].get(skill, 1)
            xp = state["skill_xp"].get(skill, 0)
            needed = 70 + level * 35
            st.markdown(f"**{skill}** {tooltip_badge(TRAINING_TOOLTIPS.get(skill, 'Improves related business outcomes.'))}", unsafe_allow_html=True)
            st.progress(level / 10, text=f"Level {level}")
            st.caption(f"{xp:.0f}/{needed:.0f} XP toward next level")

    actions = st.session_state.weekly_actions
    st.subheader("Training Plan For Next Week")
    with st.form("training_form"):
        new_training = {}
        cols = st.columns(2)
        total_hours = 0
        total_cost = 0
        for index, skill in enumerate(SKILLS):
            current = int(actions.get("training", {}).get(skill, 0))
            with cols[index % 2]:
                hours = st.number_input(
                    skill,
                    min_value=0,
                    max_value=12,
                    value=current,
                    step=1,
                    key=f"train_{skill}",
                    help=f"Training this skill costs $65/hour and consumes founder time next week. {TRAINING_TOOLTIPS.get(skill, '')}",
                )
            new_training[skill] = hours
            total_hours += hours
            total_cost += hours * 65
        st.caption(f"Training plan uses {total_hours} hours and costs {money(total_cost)} next week.")
        if st.form_submit_button(
            "Save Training Plan",
            type="primary",
            use_container_width=True,
            help="Saves the hours to spend on skill improvement next week. Training cost and time are applied when you run the week.",
        ):
            actions["training"] = new_training
            st.session_state.weekly_actions = actions
            st.success("Training plan saved.")

    render_run_week_button("Run Week With Training", key="training_run_week")


def reports_page():
    state = st.session_state.game
    page_header("Reports", "Review unit economics, channel quality, cash movement, and growth constraints.")
    df = history_df()
    cdf = channel_df()

    cols = st.columns(4)
    total_revenue = state["metrics"].get("total_revenue", 0)
    total_expenses = state["metrics"].get("total_expenses", 0) + state["metrics"].get("total_campaign_spend", 0)
    margin = (total_revenue - total_expenses) / total_revenue if total_revenue else 0
    avg_client_value = state["mrr"] / max(1, len(active_clients(state)))
    estimated_ltv = avg_client_value * 6
    churn_rate = state["metrics"].get("lifetime_churned_clients", 0) / max(1, state["metrics"].get("lifetime_clients_closed", 0))
    cols[0].metric("Total Revenue", money(total_revenue), help="Lifetime simulated revenue from retainers and setup fees.")
    cols[1].metric("Profit Margin", percent(margin), help="Lifetime profit divided by revenue. Campaign spend, payroll, training, and tools reduce this.")
    cols[2].metric("Est. Client LTV", money(estimated_ltv), help="Simple estimate based on current average client value and assumed six-month retention.")
    cols[3].metric("Client Churn", percent(churn_rate), help="Share of closed clients that have churned. Delivery overload and low satisfaction increase this.")

    chart_cols = st.columns(2)
    with chart_cols[0]:
        svg_chart_panel(
            "Revenue, Costs, Profit",
            [
                {"label": "Revenue", "color": "#1f9d55", "values": df["revenue"].tolist()},
                {"label": "Costs", "color": "#c53030", "values": df["expenses"].tolist()},
                {"label": "Profit", "color": "#b7791f", "values": df["profit"].tolist()},
            ],
        )
    with chart_cols[1]:
        svg_chart_panel(
            "Cash And Clients",
            [
                {"label": "Cash", "color": "#0f9f8c", "values": df["cash"].tolist()},
                {"label": "Active clients", "color": "#7c3aed", "values": df["active_clients"].tolist()},
            ],
        )

    st.subheader("Channel Unit Economics")
    st.markdown(
        tooltip_line(
            "Unit economics",
            "Use this to see which channels generate clients profitably. Cost per client and close rate matter more than raw lead volume.",
        ),
        unsafe_allow_html=True,
    )
    st.dataframe(
        formatted_channel_df(),
        use_container_width=True,
        hide_index=True,
        column_config=channel_column_config(),
    )


def achievements_page():
    state = st.session_state.game
    page_header("Achievements", "Milestones reward durable business progress, not just vanity metrics.")
    unlocked = set(state.get("achievements", []))
    cols = st.columns(2)
    for index, achievement in enumerate(ACHIEVEMENTS):
        with cols[index % 2]:
            status = "Unlocked" if achievement["id"] in unlocked else "Locked"
            st.markdown(
                f"""
                <div class="lg-panel">
                  <div class="lg-small-label">{status}</div>
                  <strong>{achievement['name']}{tooltip_badge('Unlocking this achievement grants XP and slightly improves reputation.')}</strong>
                  <div class="lg-subtle">{achievement['description']}</div>
                  <div class="lg-subtle">{achievement['xp']} XP</div>
                </div>
                """,
                unsafe_allow_html=True,
            )


def settings_page():
    page_header("Settings / Save Game", "Progress is stored locally in SQLite. Autosave runs after every simulated week and major purchase.")
    state = st.session_state.game
    cols = st.columns(3)
    if cols[0].button("Manual Save", type="primary", use_container_width=True, help="Writes the current game state to local storage. Autosave also runs after major actions."):
        persist()
        st.success("Saved.")
    if cols[1].button("Load Saved Game", use_container_width=True, help="Loads the local saved game slot from SQLite or JSON fallback."):
        saved = load_game()
        if saved:
            st.session_state.game = saved
            st.success("Loaded.")
            st.rerun()
        else:
            st.warning("No save found.")
    if cols[2].button("Reset Game", use_container_width=True, help="Deletes the current save slot and starts a fresh business."):
        delete_save()
        st.session_state.game = new_game()
        st.session_state.weekly_actions = default_actions()
        persist()
        st.warning("Game reset.")
        st.rerun()

    st.subheader("Local Save Location")
    st.code(f"Primary SQLite: {DB_PATH}\nFallback JSON: {JSON_FALLBACK_PATH}")

    st.subheader("Phone Access On Same WiFi")
    st.markdown(
        f"""
        Start the app with the network address enabled, then open this from your phone browser:

        `{get_lan_hint()}`

        If the phone cannot connect, allow Python or Streamlit through your computer firewall and confirm both devices are on the same WiFi network.
        """
    )
    st.code("pip install -r requirements.txt\nstreamlit run app.py --server.address 0.0.0.0", language="bash")

    st.subheader("Current State Snapshot")
    st.json(
        {
            "week": state["week"],
            "cash": round(state["cash"], 2),
            "mrr": round(state["mrr"], 2),
            "monthly_expenses": round(state["monthly_expenses"], 2),
            "clients": len(active_clients(state)),
            "team": len(state.get("team", [])),
            "tools": len(state.get("tools", [])),
            "save_file": str(DB_PATH),
            "fallback_save_file": str(JSON_FALLBACK_PATH),
        }
    )


def sidebar():
    state = st.session_state.game
    st.sidebar.title("LeadGen Tycoon")
    st.sidebar.caption(f"Week {state['week']} | Level {state['level']} | {state['stage']}")
    cash_tip = KPI_TOOLTIPS["Cash"]
    mrr_tip = KPI_TOOLTIPS["MRR"]
    st.sidebar.markdown(
        f"""
        <div class="lg-sidebar-kpis">
          <div class="lg-sidebar-kpi" title="{escape(cash_tip, quote=True)}"><span>Cash {tooltip_badge(cash_tip)}</span><strong>{money(state["cash"])}</strong></div>
          <div class="lg-sidebar-kpi" title="{escape(mrr_tip, quote=True)}"><span>MRR {tooltip_badge(mrr_tip)}</span><strong>{money(state["mrr"])}</strong></div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    selected_nav = st.sidebar.radio(
        "Sections",
        NAV_ITEMS,
        key="nav_radio",
        help="Switch between views. Navigation does not advance time, spend money, or change simulation results.",
    )
    st.session_state.nav = selected_nav
    if st.sidebar.button(
        "Run Planned Week",
        key="sidebar_run_planned_week",
        type="primary",
        use_container_width=True,
        help="Simulates one week using the saved campaign and training plan. Results are autosaved.",
    ):
        run_week()
        st.rerun()
    if st.session_state.get("save_error"):
        st.sidebar.warning(st.session_state.save_error)
    st.sidebar.caption("Autosaves after every turn, purchase, hire, cancellation, or reset.")
    return selected_nav


def main():
    init_session()
    nav = sidebar()
    if nav == "Dashboard":
        dashboard_page()
    elif nav == "Run Campaigns":
        run_campaigns_page()
    elif nav == "Tools / Subscriptions":
        tools_page()
    elif nav == "Hiring":
        hiring_page()
    elif nav == "Clients":
        clients_page()
    elif nav == "Skills / Training":
        skills_page()
    elif nav == "Reports":
        reports_page()
    elif nav == "Achievements":
        achievements_page()
    elif nav == "Settings / Save Game":
        settings_page()
    flush_notifications()


if __name__ == "__main__":
    main()
